name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GCHR
      users: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/neshmi/axiell-collections-exporter:$(date +%s)
        docker push ghcr.io/neshmi/axiell-collections-exporter:$(date +%s)
